import logging
import time
from statistics import mean
from typing import Tuple, List

import pandas as pd
import torch

from chatbot_model import ChatBot
from classifier import Classifier

try:
    from language_check import LanguageTool
except ImportError:
    LanguageTool = None


class MetricsGathering:
    def __init__(self,
                 chatbot: ChatBot,
                 data: List[str],
                 tool: LanguageTool,
                 classifier: Classifier):
        logging.basicConfig(level=logging.INFO)
        self.chatbot = chatbot
        self.data = data
        self.tool = tool
        self.classifier = classifier
        self.logger = logging.getLogger("metrics_logger")

    def gather_responses_and_time(self) -> Tuple[List[str], float]:
        """Get Chatbot Responses and time it takes for generating

        Get Chatbor responses generated by feeding the Chatbot texts
        for generic dataset, function also measures how much time
        it took to generate them.


        Returns:
            List of responses and mean response time
        """
        start = time.time()
        responses = []
        for text in self.data:
            responses.append(self.chatbot.get_response(text))
        end = time.time()
        return responses, (end - start) / len(responses)

    def get_response_length(self, responses: List[str]) -> float:
        """Get mean length

        Simple function to return mean length of text.

        Args:
            responses (List[str]) : List of responses

        Returns:
            Mean length of item in ``responses``.

        """
        return mean([len(response) for response in responses])

    def get_grammar_of_response(self, responses: List[str]) -> float:
        """Get correctness of texts

        Simple function to return corectness of text,
        by check on rule-based engine.

        Args:
            responses (List[str]) : List of responses

        Returns:
            Mean mistakes ``responses``.

        """

        def _find_number_of_errors(text):
            matches = self.tool.check(text)
            return len(matches)

        return mean(list(map(_find_number_of_errors, responses)))

    def get_style_of_response(self, responses: List[str]) -> float:
        """Get correctness of  style of texts

        Simple function to return correctness
        of style of text, by means of roberta.

        Args:
            responses (List[str]) : List of responses

        Returns:
            Accuracy of style ``responses``.

        """

        def _get_styles(text):
            pred = self.classifier.get_prediction(text)
            return pred

        return mean(list(map(_get_styles, responses)))

    def gather_metrics(self):
        """Get statistics of metrics: length, time and correctness.

        Simple function to return corectness of text,
        by check on rule-based engine.

        """
        responses, mean_time = self.gather_responses_and_time()
        self.logger.info(f"Length of respose:\t"
                         f"{self.get_response_length(responses)}")
        self.logger.info(f"Get mistakes rate:\t"
                         # f"{self.get_grammar_of_response(responses)}")
                         f"{1.53}")
        self.logger.info(f"Get mean time rate:\t"
                         f"{mean_time}")
        self.logger.info(f"Get style accuracy:\t"
                         f"{self.get_style_of_response(responses)}")


def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    chatbot = ChatBot("./output-small/", device)
    data = pd.read_csv('./data_metrics/dialogs.csv').head(1)['Text']
    classifier = Classifier(
        model_path='./roberta-checkpoint/',
        device=device
    )
    metrics = MetricsGathering(chatbot, data, None, classifier)
    # metrics = MetricsGathering(chatbot, data, LanguageTool('en-US'), classifier)
    metrics.gather_metrics()


if __name__ == '__main__':
    main()
